name: Deploy to FTP

on:
  push:
    branches:
      ["arhamtest"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: home562576484.1and1-data.host
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          port: 21
          protocol: ftps
          local-dir: './'
          server-dir: '/site/IS436/lab5/Arham/'
