name: Deploy to FTP

on:
  push:
    branches:
      - main  # Change "main" to your branch name if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@2.0.0
        with:
          server: home562576484.1and1-data.host
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          local-dir: './'
          remote-dir: '/site/IS436/lab5/Arham/'
          port: 22
          protocol: sftp
